remote_theme: nikurusov/minima

google_site_verification: o2Ycmmb2b2Y-7--UFooD7gdPQV4H7I-dbvf1WHI00QA
author: Mikalai Urusau
title: nikurusov

url: "https://nikurusov.github.io"
baseurl: ""

description: "Mikalai Urusau — Scala and JVM engineer focused on performance and internals"

include:
  - robots.txt

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
