remote_theme: nikurusov/minima

google_site_verification: o2Ycmmb2b2Y-7--UFooD7gdPQV4H7I-dbvf1WHI00QA
author: Nikita Urusov
title: nikurusov

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
